server:
  port: 0
spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/switht_payment
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092


imp:
  code: imp00575764
  key: 3703707833671424
  secret: Guer6P3tAcUQRDGf34DZCVYDHjkuNAfaH6k0wr39NXLDkn2pfOgwzcd7FHP6NYeh1dYmcnKevqL8EfMG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/